import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Adjust weights as needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className="md:max-w-2xl md:px-0 px-4 mx-auto mt-8 bg-[#141414]">
        <main>
          <div className="min-h-screen flex flex-col">
            {/* <Header /> */}
            <main>
              {children}
            </main>
            {/* <Footer /> */}
          </div>
        </main>
      </body>
    </html>
  );
}

// className="mx-auto py-32 relative max-w-2xl min-h-screen overflow-hidden sm:overflow-visible px-6 sm:px-0"